# Generated by Django 4.1.7 on 2023-02-20 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MilitaryMuseum', '0017_alter_combatants_details_alter_combatants_issue_year_and_more'),
        ('userprofile', '0002_userprofile_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MilitaryMuseum.ranks'),
        ),
    ]
