# Generated by Django 4.1.7 on 2023-02-20 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_userprofile_name_userprofile_patronymic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='rank',
        ),
    ]
