# Generated by Django 4.1.5 on 2023-01-25 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combatants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=70)),
                ('rank', models.CharField(max_length=70)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(max_length=100)),
                ('combatant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MilitaryMuseum.combatants')),
            ],
        ),
    ]
