# Generated by Django 4.1.5 on 2023-01-25 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MilitaryMuseum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combatants',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='pictures',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AddField(
            model_name='combatants',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='combatants',
            name='date_of_death',
            field=models.DateField(null=True, verbose_name='Дата смерти'),
        ),
        migrations.AlterField(
            model_name='combatants',
            name='details',
            field=models.TextField(verbose_name='Подробности'),
        ),
        migrations.AlterField(
            model_name='combatants',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='combatants',
            name='rank',
            field=models.CharField(max_length=70, null=True, verbose_name='Звание'),
        ),
        migrations.AlterField(
            model_name='combatants',
            name='surname',
            field=models.CharField(max_length=70, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='combatant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MilitaryMuseum.combatants', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='picture',
            field=models.CharField(max_length=100, verbose_name='Название изображения'),
        ),
    ]
