# Generated by Django 4.1.5 on 2023-01-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MilitaryMuseum', '0003_combatants_native_city_alter_combatants_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='picture',
            field=models.ImageField(upload_to='images/', verbose_name='Изображение'),
        ),
    ]
