# Generated by Django 4.1.5 on 2023-01-27 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MilitaryMuseum', '0004_alter_pictures_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='videos/', verbose_name='Видео')),
                ('combatant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MilitaryMuseum.combatants', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
    ]
