# Generated by Django 4.1.5 on 2023-01-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MilitaryMuseum', '0005_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatants',
            name='battalion',
            field=models.CharField(max_length=100, null=True, verbose_name='Батальон'),
        ),
        migrations.AddField(
            model_name='combatants',
            name='issue_year',
            field=models.IntegerField(max_length=4, null=True, verbose_name='Год выпуска'),
        ),
    ]
