# Generated by Django 4.1.5 on 2023-01-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MilitaryMuseum', '0006_combatants_battalion_combatants_issue_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combatants',
            name='issue_year',
            field=models.IntegerField(null=True, verbose_name='Год выпуска'),
        ),
    ]
