# Generated by Django 4.1.5 on 2023-01-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MilitaryMuseum', '0007_alter_combatants_issue_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='picture',
            new_name='video',
        ),
        migrations.AddField(
            model_name='combatants',
            name='patronymic',
            field=models.CharField(max_length=70, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='pictures',
            name='is_main_picture',
            field=models.BooleanField(default=False, verbose_name='Является главной фотографией'),
        ),
    ]
