# Generated by Django 4.1.5 on 2023-01-28 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MilitaryMuseum', '0009_cities_alter_combatants_native_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='Место')),
            ],
            options={
                'verbose_name': 'Места',
                'verbose_name_plural': 'Места рождения',
            },
        ),
        migrations.RemoveField(
            model_name='combatants',
            name='native_city',
        ),
        migrations.AlterField(
            model_name='combatants',
            name='battalion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Батальон'),
        ),
        migrations.AlterField(
            model_name='combatants',
            name='date_of_birth',
            field=models.DateField(blank=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='combatants',
            name='date_of_death',
            field=models.DateField(blank=True, verbose_name='Дата смерти'),
        ),
        migrations.AlterField(
            model_name='combatants',
            name='details',
            field=models.TextField(blank=True, verbose_name='Подробности'),
        ),
        migrations.AlterField(
            model_name='combatants',
            name='issue_year',
            field=models.IntegerField(blank=True, verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='combatants',
            name='patronymic',
            field=models.CharField(blank=True, max_length=70, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='combatants',
            name='rank',
            field=models.CharField(blank=True, max_length=70, verbose_name='Звание'),
        ),
        migrations.DeleteModel(
            name='Cities',
        ),
        migrations.AddField(
            model_name='combatants',
            name='place_of_birth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MilitaryMuseum.places', verbose_name='Место рождения'),
            preserve_default=False,
        ),
    ]
