# Generated by Django 4.1.5 on 2023-02-13 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MilitaryMuseum', '0011_bgpictures_alter_combatants_place_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgpictures',
            name='picture',
            field=models.ImageField(upload_to='images/backgrounds/', verbose_name='Фоновое изображение'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg'])], verbose_name='Видео'),
        ),
    ]
