# Generated by Django 4.1.5 on 2023-02-13 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MilitaryMuseum', '0013_ranks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combatants',
            name='rank',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='MilitaryMuseum.ranks', verbose_name='Звание'),
        ),
    ]
