# Generated by Django 4.1.5 on 2023-02-14 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MilitaryMuseum', '0015_alter_combatants_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combatants',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MilitaryMuseum.ranks', verbose_name='Звание'),
        ),
    ]
